version: '3.8'
services:
  mongo:
    image: mongo
    container_name: "mongo-database"
    restart: always
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017
    networks:
      - WServiceNetwork

  app_service_global:
    container_name: 'go-global'
    image: go-global
    build:
       context: .
       dockerfile: Warehouse-Service-Global/Dockerfile
    ports:
       - "5554:5554"
    depends_on:
       - 'mongo'

  app_service_input:
    container_name: 'go-input'
    image: go-input
    build:
      context: .
      dockerfile: Warehouse-Service-Input/Dockerfile
    ports:
      - "8554:8554"
    depends_on:
      - 'mongo'

  app_service_master:
    container_name: 'go-master'
    image: go-master
    build:
      context: .
      dockerfile: /Warehouse-Service-Master/Dockerfile
    ports:
      - '7554:7554'
    depends_on:
      - 'mongo'

  app_service_output:
    container_name: 'go-output'
    image: go-output
    build:
      context: .
      dockerfile: Warehouse-Service-Output/Dockerfile
    ports:
      - "9554:9554"
    depends_on:
      - 'mongo'

  app_service_reject:
    container_name: 'go-reject'
    image: go-reject
    build:
      context: .
      dockerfile: Warehouse-Service-Reject/Dockerfile
    ports:
      - '6554:6554'
    depends_on:
      - 'mongo'

networks:
  WServiceNetwork:
    driver: bridge