version: '3.8'
services:
  mongo:
    image: mongo
    container_name: "mongo-database"
    restart: always
    environment:
      MONGO_INITDB_ROOT_DATABASE: WServiceMaster
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017

  app_service_global:
    container_name: 'go-global'
    image: aboutindra/go-global
    command: bash -c "cd Warehouse-Service-Global && docker build -t go-global ."
    ports:
       - "5554:5554"
    depends_on:
       - 'mongo'

  app_service_input:
    container_name: 'go-input'
    image: aboutindra/go-input
    command: bash -c "cd Warehouse-Service-Input && docker build -t go-input ."
    ports:
      - "8554:8554"
    depends_on:
      - 'mongo'

  app_service_master:
    container_name: 'go-master'
    image: aboutindra/go-master
    command: bash -c "cd Warehouse-Service-Master && docker build -t go-master ."
    ports:
      - '7554:7554'
    depends_on:
      - 'mongo'

  app_service_output:
    container_name: 'go-output'
    image: aboutindra/go-output
    command: bash -c "cd Warehouse-Service-Output && docker build -t go-output ."
    ports:
      - "9554:9554"
    depends_on:
      - 'mongo'

  app_service_reject:
    container_name: 'go-reject'
    image: aboutindra/go-reject
    command: bash -c "cd Warehouse-Service-Reject && docker build -t go-reject ."
    ports:
      - '6554:6554'
    depends_on:
      - 'mongo'

networks:
  WServiceNetwork:
    driver: bridge