version: '3.8'
services:
  mongo:
    image: mongo
    container_name: "mongo-master"
    restart: always
    environment:
      MONGO_INITDB_ROOT_DATABASE: WServiceMaster
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017

  app:
    container_name: 'go-master'
    image: go-master
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7554:7554'
    depends_on:
      - 'mongo'

networks:
  WServiceMasterNetwork:
    driver: bridge
