version: '3.8'
services:
  mongo:
    image: mongo
    container_name: "mongo-reject"
    restart: always
    environment:
      MONGO_INITDB_ROOT_DATABASE: WServiceReject
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017

  app:
    container_name: 'go-reject'
    image: go-reject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6554:6554'
    depends_on:
      - 'mongo'

networks:
  WServiceRejectNetwork:
    driver: bridge
